[features]
seeds = false
[programs.localnet]
solana_task = "AE3UkQZZVGMv4tHVgRVZX3ubBtemruQJPTpFDsYpjUtY"

[registry]
url = "https://anchor.projectserum.com"

[provider]
#cluster = "localnet"
cluster = "https://api.devnet.solana.com"
wallet = "/home/artem/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
